title: MUKASHI Sound
description: 日本の風景歌や童謡歌などの懐かしの音楽を車で聞けるアプリ
theme: just-the-docs

baseurl: "/mukashisound"
url: https://mikkikimasutaro.github.io
github_username: mikkikimasutaro

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

footer_content: "Copyright &copy; 2023 mikkikimasutaro"