title: MUKASHI Sound
description: 日本の風景歌や童謡歌などの懐かしの音楽を車で聞けるアプリ
#theme: just-the-docs

baseurl: "/MUKASHISound"
url: https://mikkikimasutaro.github.io
github_username: mikkikimasutaro

remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
search_enabled: false
aux_links:
  "Source code on GitHub":
    - "//github.com/mikkikimasutaro/MUKASHISound/"

footer_content: "Copyright &copy; 2023 mikkikimasutaro"